site_name: C. elegans Connectome Toolbox
theme:
  name: material    
  favicon: images/favicon.ico
  logo: images/favicon.ico
  palette:
    primary: green  

nav:
  - Overview: 'index.md'
  - 'Connectomes':
    - 'White et al. 1986': 'White_1986.md'
    - 'Durbin 1987': 'Durbin_1987.md'
    - 'Altunet al. 2009': 'Altun_2009.md'
    - 'Varshney et al. 2011': 'Varshney_2011.md'
    - 'Pereira et al. 2015': 'Pereira_2015.md'
    - 'Bentley et al. 2016': 'Bentley_2016.md'
    - 'Cook et al. 2019': 'Cook_2019.md'
    - 'Brittin et al. 2021': 'Brittin_2021.md'
    - 'Witvliet et al. 2021': 'Witvliet_2021.md'
  - Python package:
    - 'Installation': 'Python.md'
