site_name: C. elegans Connectome Toolbox
theme:
  name: material
  palette:
    primary: green
nav:
  - Overview: 'index.md'
  - 'Connectomes':
    - 'White et al. 1984': 'White_1984.md'
    - 'Durbin 1987':'Durbin_1987.md'
    - 'Altunet al. 2009':'Altun_2009.md'
    - 'Varshney et al. 2011':'Varshney_2009.md'
    - 'Pereira et al. 2015':'Pereira_2015.md'
    - 'Bentley et al. 2016':'Bentley_2016.md'
    - 'Cook et al. 2019': 'Cook_2019.md'
  - Python package:
    - 'Installation': 'Python.md'
